apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-webapp
  labels:
    app: static-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-webapp
  template:
    metadata:
      labels:
        app: static-webapp
    spec:
      containers:
      - name: static-webapp
        image: <your-account-id>.dkr.ecr.us-west-2.amazonaws.com/static-webapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-webapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    #service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack --> for IPv6 Cluster
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: static-webapp
  type: LoadBalancer

