apiVersion: v1
kind: Pod
metadata:
  name: init-demo.
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent  
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    initContainers:
  - name: install
    image: alpine
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - https://github.com/dubareddy/testcode/blob/master/index.html?raw=true
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}