apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod 
spec:
  volumes:
  - name: shared-date-logs  
    emptyDir: {}            
  containers:
  - name: container-writing-dates 
    image: alpine 
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"] 
    volumeMounts:
    - name: shared-date-logs
      mountPath: /var/log 
      
  - name: container-serving-dates 
    image: nginx:1.19.0 
    ports:
      - containerPort: 80 
        hostPort: 8090
    volumeMounts:
    - name: shared-date-logs
      mountPath: /usr/share/nginx/html 