apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-webapp
  labels:
    app: static-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-webapp
  template:
    metadata:
      labels:
        app: static-webapp
    spec:
      containers:
      - name: static-webapp
        image: 660665532013.dkr.ecr.ap-south-1.amazonaws.com/static-webapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: static-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
