kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
spec: 
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
    - key: "dev"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

